use crate::note::{note, Note, NoteDesc};

pub static NOTES: [NoteDesc; 144] = [
    note(Note::SILENCE, 7, 50),
    note(Note::G, 7, 12),
    note(Note::FS, 7, 12),
    note(Note::E, 7, 12),
    note(Note::SILENCE, 7, 1),
    note(Note::E, 7, 12),
    // ===
    note(Note::FS, 7, 50),
    note(Note::SILENCE, 7, 50),
    // ===
    note(Note::SILENCE, 7, 12),
    note(Note::SILENCE, 7, 25),
    note(Note::A, 6, 12),
    note(Note::G, 7, 12),
    note(Note::FS, 7, 12),
    note(Note::E, 7, 12),
    note(Note::SILENCE, 7, 1),
    note(Note::E, 7, 12),
    // ===
    note(Note::E, 7, 12),
    note(Note::FS, 7, 37),
    note(Note::D, 7, 25),
    note(Note::E, 7, 12),
    note(Note::A, 6, 12),
    // =====
    // =====
    note(Note::A, 6, 50),
    note(Note::SILENCE, 7, 37),
    note(Note::A, 6, 12),
    // ===
    note(Note::E, 7, 25),
    note(Note::FS, 7, 12),
    note(Note::G, 7, 12),
    note(Note::G, 7, 25),
    note(Note::E, 7, 12),
    note(Note::CS, 7, 12),
    // ===
    note(Note::SILENCE, 7, 1),
    note(Note::CS, 7, 12),
    note(Note::D, 7, 37),
    note(Note::E, 7, 25),
    note(Note::A, 6, 12),
    note(Note::SILENCE, 7, 1),
    note(Note::A, 6, 12),
    // ===
    note(Note::A, 6, 12),
    note(Note::FS, 7, 37),
    note(Note::SILENCE, 7, 50),
    // =====
    // =====
    note(Note::SILENCE, 7, 50),
    note(Note::G, 7, 12),
    note(Note::FS, 7, 12),
    note(Note::E, 7, 12),
    note(Note::SILENCE, 7, 1),
    note(Note::E, 7, 12),
    // ===
    note(Note::FS, 7, 50),
    note(Note::SILENCE, 7, 50),
    // ===
    note(Note::SILENCE, 7, 25),
    note(Note::SILENCE, 7, 12),
    note(Note::A, 6, 12),
    note(Note::G, 7, 12),
    note(Note::FS, 7, 12),
    note(Note::E, 7, 12),
    note(Note::SILENCE, 7, 1),
    note(Note::E, 7, 12),
    // ===
    note(Note::E, 7, 25),
    note(Note::FS, 7, 12),
    note(Note::D, 7, 12),
    note(Note::SILENCE, 7, 1),
    note(Note::D, 7, 25),
    note(Note::E, 7, 12),
    note(Note::A, 6, 12),
    // =====
    // =====
    note(Note::A, 6, 50),
    note(Note::SILENCE, 7, 50),
    // ===
    note(Note::E, 7, 25),
    note(Note::FS, 7, 12),
    note(Note::G, 7, 12),
    note(Note::SILENCE, 7, 1),
    note(Note::G, 7, 25),
    note(Note::E, 7, 12),
    note(Note::CS, 7, 12),
    // ===
    note(Note::SILENCE, 7, 1),
    note(Note::CS, 7, 25),
    note(Note::D, 7, 12),
    note(Note::E, 7, 12),
    note(Note::SILENCE, 7, 1),
    note(Note::E, 7, 12),
    note(Note::A, 6, 12),
    note(Note::D, 7, 12),
    note(Note::E, 7, 12),
    // =====
    // =====
    note(Note::F, 7, 12),
    note(Note::E, 7, 12),
    note(Note::D, 7, 12),
    note(Note::C, 7, 12),
    note(Note::SILENCE, 7, 25),
    note(Note::A, 6, 12),
    note(Note::BB, 6, 12),
    // ===
    note(Note::C, 7, 25),
    note(Note::F, 7, 25),
    note(Note::E, 7, 12),
    note(Note::D, 7, 12),
    note(Note::SILENCE, 7, 1),
    note(Note::D, 7, 12),
    note(Note::C, 7, 12),
    // ===
    note(Note::D, 7, 12),
    note(Note::C, 7, 12),
    note(Note::SILENCE, 7, 1),
    note(Note::C, 7, 25),
    note(Note::SILENCE, 7, 1),
    note(Note::C, 7, 25),
    note(Note::A, 6, 12),
    note(Note::BB, 6, 12),
    // =====
    // =====
    note(Note::C, 7, 25),
    note(Note::F, 7, 25),
    note(Note::G, 7, 12),
    note(Note::F, 7, 12),
    note(Note::E, 7, 12),
    note(Note::D, 7, 12),
    // ===
    note(Note::SILENCE, 7, 1),
    note(Note::D, 7, 12),
    note(Note::E, 7, 12),
    note(Note::F, 7, 25),
    note(Note::SILENCE, 7, 1),
    note(Note::F, 7, 25),
    note(Note::G, 7, 12),
    note(Note::A, 7, 12),
    // ===
    note(Note::B, 7, 12),
    note(Note::SILENCE, 7, 1),
    note(Note::B, 7, 12),
    note(Note::A, 7, 25),
    note(Note::G, 7, 25),
    note(Note::F, 7, 12),
    note(Note::G, 7, 12),
    // =====
    // =====
    note(Note::A, 7, 12),
    note(Note::SILENCE, 7, 1),
    note(Note::A, 7, 12),
    note(Note::G, 7, 25),
    note(Note::F, 7, 25),
    note(Note::SILENCE, 7, 1),
    note(Note::D, 7, 12),
    note(Note::C, 7, 12),
    // ===
    note(Note::D, 7, 12),
    note(Note::F, 7, 12),
    note(Note::SILENCE, 7, 1),
    note(Note::F, 7, 12),
    note(Note::E, 7, 12),
    note(Note::SILENCE, 7, 1),
    note(Note::E, 7, 12),
    note(Note::SILENCE, 7, 1),
    note(Note::E, 7, 12),
    note(Note::GB, 7, 12),
    note(Note::SILENCE, 7, 1),
    note(Note::GB, 7, 12),
];
